spring:
  profiles.active: prod
  application.name: follow-insider

### Server ###
server:
  port: 5000
  tomcat.remoteip:
    protocol-header: X-Forwarded-Proto
    remote-ip-header: X-Forwarded-For

### Database ###
spring.jpa:
  database: POSTGRESQL
  hibernate.ddl-auto: update
  open-in-view: true
  properties.hibernate:
    jdbc.lob.non_contextual_creation: true
    jdbc.batch_size: 32
    order_inserts: true
    order_updates: false

### Logging ###
logging.file.name: logs/app.log

### EDGAR ###
edgar.user_agent: Alexey Kovzel alexey.kovzel@gmail.com