spring:
  profiles.active: dev
  application.name: follow-insider

logging.file.name: logs/app.log

app:
  auto_form_sync: ${AUTO_FORM_SYNC}
  edgar_user_agent: ${EDGAR_USER_AGENT}

email:
  username: ${EMAIL_USERNAME}
  password: ${EMAIL_PASSWORD}
  sender: ${EMAIL_SENDER}

server:
  port: 5000
  tomcat.remoteip:
    protocol-header: X-Forwarded-Proto
    remote-ip-header: X-Forwarded-For

spring.jpa:
  database: POSTGRESQL
  hibernate.ddl-auto: update
  open-in-view: true
  properties.hibernate:
    jdbc.lob.non_contextual_creation: true
    jdbc.batch_size: 32
    order_inserts: true
    order_updates: false
